// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mocks/handler.go -package=mocks .
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStopWordList is a mock of StopWordList interface.
type MockStopWordList struct {
	ctrl     *gomock.Controller
	recorder *MockStopWordListMockRecorder
	isgomock struct{}
}

// MockStopWordListMockRecorder is the mock recorder for MockStopWordList.
type MockStopWordListMockRecorder struct {
	mock *MockStopWordList
}

// NewMockStopWordList creates a new mock instance.
func NewMockStopWordList(ctrl *gomock.Controller) *MockStopWordList {
	mock := &MockStopWordList{ctrl: ctrl}
	mock.recorder = &MockStopWordListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopWordList) EXPECT() *MockStopWordListMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStopWordList) Add(words []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", words)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStopWordListMockRecorder) Add(words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStopWordList)(nil).Add), words)
}

// Delete mocks base method.
func (m *MockStopWordList) Delete(words []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", words)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStopWordListMockRecorder) Delete(words any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStopWordList)(nil).Delete), words)
}

// MockRawTopQueriesList is a mock of RawTopQueriesList interface.
type MockRawTopQueriesList struct {
	ctrl     *gomock.Controller
	recorder *MockRawTopQueriesListMockRecorder
	isgomock struct{}
}

// MockRawTopQueriesListMockRecorder is the mock recorder for MockRawTopQueriesList.
type MockRawTopQueriesListMockRecorder struct {
	mock *MockRawTopQueriesList
}

// NewMockRawTopQueriesList creates a new mock instance.
func NewMockRawTopQueriesList(ctrl *gomock.Controller) *MockRawTopQueriesList {
	mock := &MockRawTopQueriesList{ctrl: ctrl}
	mock.recorder = &MockRawTopQueriesListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawTopQueriesList) EXPECT() *MockRawTopQueriesListMockRecorder {
	return m.recorder
}

// GetTopJSON mocks base method.
func (m *MockRawTopQueriesList) GetTopJSON() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopJSON")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetTopJSON indicates an expected call of GetTopJSON.
func (mr *MockRawTopQueriesListMockRecorder) GetTopJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopJSON", reflect.TypeOf((*MockRawTopQueriesList)(nil).GetTopJSON))
}

// MockStructedTopQueriesList is a mock of StructedTopQueriesList interface.
type MockStructedTopQueriesList struct {
	ctrl     *gomock.Controller
	recorder *MockStructedTopQueriesListMockRecorder
	isgomock struct{}
}

// MockStructedTopQueriesListMockRecorder is the mock recorder for MockStructedTopQueriesList.
type MockStructedTopQueriesListMockRecorder struct {
	mock *MockStructedTopQueriesList
}

// NewMockStructedTopQueriesList creates a new mock instance.
func NewMockStructedTopQueriesList(ctrl *gomock.Controller) *MockStructedTopQueriesList {
	mock := &MockStructedTopQueriesList{ctrl: ctrl}
	mock.recorder = &MockStructedTopQueriesListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStructedTopQueriesList) EXPECT() *MockStructedTopQueriesListMockRecorder {
	return m.recorder
}

// GetTopN mocks base method.
func (m *MockStructedTopQueriesList) GetTopN(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTopN", n)
}

// GetTopN indicates an expected call of GetTopN.
func (mr *MockStructedTopQueriesListMockRecorder) GetTopN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopN", reflect.TypeOf((*MockStructedTopQueriesList)(nil).GetTopN), n)
}
